---
title: "Conceptos Básicos"
editor: visual
author: "Fabián Brenes Trejos"
toc: true
bibliography: ../references.bib
number-sections: true
code-fold: true
html-math-method: katex
theme:
  - cosmo
  - ../../Plantillas/fmbt_doc.scss
---

# Tipo de datos

```{mermaid}
 
flowchart TD
    A[Tipos de Datos] 

    A --> B[Continuos]
    A --> C[Discretos]
    B --> D["`Ejemplos:
    - Tasa de interés
    - Producto Interno Bruto`"]
    C --> E[Nominal]
    E --> G["`Ejemplos:
    - Verdadero o Falso
    - Activo o Inactivo`"]
    C --> F[Ordinal]
    F --> H["`Ejemplos:
    - 1 = Bajo, 2= Moderado, 3= Severo
    -1 = Deficiente, 2 = Aceptable, 3 = Bueno`"]

```

# Estadísticos generales

Los estadísticos descriptivos generales para datos cuantitativos se agrupan en [@HLee2023]:

## Medidas de tendencia central

### Media

Suma de todas las observaciones dividida por el total de observaciones

$$
\begin{equation}
    \bar{x} = \frac{1}{n}(x_1 + x_2 + \dots{} +  x_n) =\sum ^ n _ {i=1}  x_i,
\end{equation} 
$$

### Mediana

Valor del medio.

### Moda

El valor más frecuente.

## Medidas de Dispersión

### Varianza

Es el promedio de la desviación de la media al cuadrado. Entre mayor es este indicador, mayor dispersión hay en la data.

$$ 
\begin{equation}
    \sigma ^ 2  = \frac {\sum ^ n _ {i=1}  (x_i - \bar{x}) ^ 2}{n - 1}
\end{equation}
$$

### Desviación Estándar

Raíz cuadrada de la varianza, con la característica de que el indicador está en la misma escala que los datos.

$$ 
\begin{equation}
    \sigma   = \sqrt{\frac {\sum ^ n _ {i=1}  (x_i - \bar{x}) ^ 2}{n - 1}} 
\end{equation}
$$

### Coeficiente de Variación

Debido a que la desviación estándar y el promedio están en la misma escala, al dividir ambos estadísticos y multiplicar por 100, se obtiene el nivel de dispersión en una escala estándar, que funciona para comparar el grado de dispersión entre distintas distribuciones de datos.

$$
\begin{equation}
    CV = \frac{\sigma}{\bar{x}} * 100
\end{equation}
$$

# Referencias
